version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - shop4shoot

  # PHP Server для СДЭК виджета
  php-server:
    image: php:8.2-cli-alpine
    working_dir: /var/www
    volumes:
      - ./widget:/var/www
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000
    restart: unless-stopped
    networks:
      - shop4shoot

  # Nginx (опционально, для проксирования)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - php-server
    restart: unless-stopped
    networks:
      - shop4shoot
    profiles:
      - with-nginx

networks:
  shop4shoot:
    driver: bridge

volumes:
  node_modules: 